name: Convert PDF to PNG

on:
  push:
    branches:
      - main

jobs:
  convert-pdf-to-png:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y poppler-utils
          
      - name: Convert PDF to PNG
        run: |
          pdftoppm -png main.pdf preview
          
      - name: Commit and push PNG
        run: |
          git add preview.png
          git commit -m "Add PNG version of the document"
          git push
